#Minecraft server properties
#Sat Jun 13 00:55:16 BST 2026
allow-flight=false
allow-nether=false
announce-player-achievements=true
debug=false
difficulty=1
enable-command-block=false
enable-query=false
enable-rcon=false
force-gamemode=false
gamemode=0
generate-structures=false
generator-settings=
hardcore=false
level-name=world
level-seed=
level-type=DEFAULT
max-build-height=256
max-players=400
max-world-size=5000
motd=A Minecraft Server
network-compression-threshold=256
online-mode=false
op-permission-level=4
player-idle-timeout=0
pvp=false
query.port=25569
resource-pack=
resource-pack-hash=
server-ip=0.0.0.0
server-port=25569
snooper-enabled=true
spawn-animals=false
spawn-monsters=false
spawn-npcs=false
spawn-protection=16
use-native-transport=true
view-distance=1
white-list=false
