package com.minecraft.core;

import com.minecraft.core.util.list.StringUtil;
import net.md_5.bungee.api.ChatColor;

import java.util.List;
import java.util.UUID;

public class Constant {

// =====================================================================
    //  MARCA DO SERVIDOR — edite tudo aqui para trocar a identidade da rede
    //  (nome, site, loja, discord, tiktok, e-mail, rede social etc.)
    //  Cada valor também pode ser sobrescrito por variável de ambiente.
    // =====================================================================

    public static final String SERVER_NAME = System.getenv().getOrDefault("SPARTA_SERVER_NAME", "Sparta");

    public static final String ARROW_SYMBOL = "»";
    public static final String ARROW_ALT_SYMBOL = "‣";
    public static final String SQUARE_SYMBOL = "▪";

    public static final String SERVER_COLOR = System.getenv().getOrDefault("SPARTA_SERVER_COLOR", "§6§l");
    public static final String SERVER_TITLE = SERVER_COLOR + ChatColor.BOLD + SERVER_NAME.toUpperCase();
    public static final String SERVER_PREFIX = SERVER_TITLE + " §7" + ARROW_SYMBOL + " §r";

    public static final String SERVER_DOMAIN = System.getenv().getOrDefault("SPARTA_SERVER_DOMAIN", "spartamc.com.br");
    public static final String SERVER_WEBSITE = "www." + SERVER_DOMAIN;
    public static final String SERVER_STORE = System.getenv().getOrDefault("SPARTA_SERVER_STORE", SERVER_WEBSITE + "/loja");
    public static final String SERVER_DISCORD = System.getenv().getOrDefault("SPARTA_SERVER_DISCORD", "https://dsc.gg/joguesparta");
    public static final String SERVER_DISCORD_GG = System.getenv().getOrDefault("SPARTA_SERVER_DISCORD_GG", "discord.gg/spartamc");
    public static final String SERVER_TIKTOK = System.getenv().getOrDefault("SPARTA_SERVER_TIKTOK", "tiktok.com/@spartamc");
    public static final String SERVER_EMAIL_DOMAIN = System.getenv().getOrDefault("SPARTA_SERVER_EMAIL_DOMAIN", "spartamc.com");

    public static final String CONFIG_DIR_NAME = System.getenv().getOrDefault("SPARTA_CONFIG_DIR", "SpartaConfig");

    public static final String SERVER_TAB_HEADER = StringUtil.StringHelper.makeCenteredMessage(
            "\n" +
                    "§6§l" + SERVER_NAME.toUpperCase() + "\n"
    );

    public static final String SERVER_TAB_FOOTER = StringUtil.StringHelper.makeCenteredMessage(
            "\n" +
                    "           §6Website: §f" + SERVER_DOMAIN + "           \n" +
                    "           §6Loja: §f" + SERVER_STORE + "           \n"
    );
    public static final String SOURCE_DIR = System.getProperty("source_dir", "com.minecraft");

    public static final UUID DEFAULT_ID = new UUID(0, 0);

    public static final UUID CHEFE_OWNER_UUID = UUID.fromString(System.getenv().getOrDefault("SPARTA_OWNER_UUID", "00000000-0000-0000-0000-000000000000"));
    public static final String CHEFE_OWNER_NAME = System.getenv().getOrDefault("SPARTA_OWNER_NAME", "");

    public static final List<UUID> DEVELOPERS_IDS = parseDeveloperIds();

    public static final String DISCORD_BOT_TOKEN = System.getenv().getOrDefault("SPARTA_DISCORD_TOKEN", "");
    public static final String DISCORD_SERVER_ID = System.getenv().getOrDefault("SPARTA_DISCORD_SERVER_ID", "");

    private static List<UUID> parseDeveloperIds() {
        String raw = System.getenv().getOrDefault("SPARTA_DEVELOPER_UUIDS", "");
        if (raw.isEmpty()) return List.of();
        java.util.ArrayList<UUID> ids = new java.util.ArrayList<>();
        for (String part : raw.split(",")) {
            try {
                ids.add(UUID.fromString(part.trim()));
            } catch (IllegalArgumentException ignored) {
            }
        }
        return java.util.Collections.unmodifiableList(ids);
    }

    public static final String MINOTAR_AVATAR_API_URL = "https://minotar.net/avatar/%s/%s";

    public static final String DATABASE_NAME = SERVER_NAME.toLowerCase();

    public static final String REDIS_ACCOUNT_UPDATE_CHANNEL = "account-update-channel";
    public static final String REDIS_ACCOUNT_RANK_UPDATE_CHANNEL = "account-rank-update-channel";
    public static final String REDIS_ACCOUNT_FRIEND_MENU_CHANNEL = "account-friend-menu-channel";
    public static final String REDIS_ACCOUNT_NICK_CHANGE_CHANNEL = "account-nick-change-channel";
    public static final String REDIS_ACCOUNT_NICKNAME_MENU_CHANNEL = "account-nickname-menu-channel";
    public static final String REDIS_ACCOUNT_SKIN_RESET_CHANNEL = "account-skin-reset-channel";
    public static final String REDIS_ROUTE_SEARCH_CHANNEL = "route-search-channel";
    public static final String REDIS_ARENA_SEARCH_CHANNEL = "arena-search-channel";
    public static final String REDIS_ARENA_STATS_CHANNEL = "arena-stats-channel";
    public static final String REDIS_ARENA_PARTY_WARP_CHANNEL = "arena-party-warp-channel";
    public static final String REDIS_ARENA_PARTY_LIST_CHANNEL = "arena-party-list-channel";
    public static final String REDIS_ACCOUNT_PUNISHMENTS_CHANNEL = "account-punishments-channel";
    public static final String REDIS_ACCOUNT_VANISH_CHANNEL = "account-vanish-channel";
    public static final String REDIS_ACCOUNT_GLOBAL_MESSAGE_CHANNEL = "account-globa-message-channel";
    public static final String REDIS_ROOM_REQUEST_CHANNEL = "room-request-channel";
    public static final String REDIS_ROOM_INFO_CHANNEL = "room-info-channel";
    public static final String REDIS_ACCOUNT_EXECUTE_COMMAND_CHANNEL = "account-execute-command-channel";
    public static final String REDIS_ACCOUNT_CLAN_CHANGE_CHANNEL = "account-clan-change-channel";
    public static final String REDIS_LOBBY_TELEPORT_CHANNEL = "lobby-teleport-channel";
    public static final String REDIS_PUNISH_OPEN_CHANNEL = "punish-open-channel";
    public static final String REDIS_PUNISH_EXECUTE_CHANNEL = "punish-execute-channel";
    public static final String REDIS_ACCOUNT_ANTICHEAT_CHANNEL = "account-anticheat-channel";

    public static final String[] REDIS_CHANNELS = new String[]{
            REDIS_ACCOUNT_UPDATE_CHANNEL, REDIS_ACCOUNT_RANK_UPDATE_CHANNEL, REDIS_ACCOUNT_FRIEND_MENU_CHANNEL,
            REDIS_ACCOUNT_NICK_CHANGE_CHANNEL, REDIS_ACCOUNT_NICKNAME_MENU_CHANNEL, REDIS_ACCOUNT_SKIN_RESET_CHANNEL, REDIS_ROUTE_SEARCH_CHANNEL,
            REDIS_ARENA_SEARCH_CHANNEL, REDIS_ARENA_STATS_CHANNEL, REDIS_ARENA_PARTY_WARP_CHANNEL, REDIS_ARENA_PARTY_LIST_CHANNEL,
            REDIS_ACCOUNT_PUNISHMENTS_CHANNEL, REDIS_ACCOUNT_VANISH_CHANNEL, REDIS_ACCOUNT_GLOBAL_MESSAGE_CHANNEL,
            REDIS_ROOM_REQUEST_CHANNEL, REDIS_ROOM_INFO_CHANNEL, REDIS_ACCOUNT_EXECUTE_COMMAND_CHANNEL,
            REDIS_ACCOUNT_CLAN_CHANGE_CHANNEL, REDIS_LOBBY_TELEPORT_CHANNEL, REDIS_PUNISH_OPEN_CHANNEL, REDIS_PUNISH_EXECUTE_CHANNEL,
            REDIS_ACCOUNT_ANTICHEAT_CHANNEL};

    public static final String SLIME_FILE_LOADER = "file";

    /* Messages */
    public static final String ACCOUNT_LOAD_FAILED_MESSAGE = "§cOcorreu um erro ao tentar carregar a sua conta!";
    public static final String SERVER_NOT_FOUND_MESSAGE = "§cNenhuma rede de %s foi encontrada.";
    public static final String NO_ROOM_AVAILABLE_MESSAGE = "§cNão há salas disponíveis.";

    public static final String INVALID_ROUTE_MESSAGE = "§cNão foi possível encontrar a sua rota.";
    public static final String ARCADE_NOT_FOUND_MESSAGE = "§cNão foi possível encontrar o modo selecionado.";

    public static final String STAFF_CHAT_PREFIX = "§d[Staff] §r";
    public static final String CLAN_CHAT_PREFIX = "§6[Clan] §r";
    public static final String PARTY_CHAT_PREFIX = "§d[Party] §r";

    public static final String BAN_TEMPLATE_MESSAGE = StringUtil.StringHelper.makeCenteredMessage(
            SERVER_TITLE + "\n\n"
                    + "§cA sua conta está %s suspensa.\n"
                    + "§cMotivo: %s\n"
                    + "§cID: %s\n"
                    + "\n"
                    + "§eAdquira seu unban em §6" + SERVER_WEBSITE + "/unban\n"
                    + "§cPunição injusta? Contate-nos em: §e" + SERVER_DISCORD + "\n");

    /* Cooldown Keys */
    public static final String CHAT_COOLDOWN_KEY = "chat-cooldown";
    public static final String TAG_CHANGE_COOLDOWN_KEY = "tag-change-cooldown";
    public static final String SKIN_CHANGE_COOLDOWN_KEY = "skin-change-cooldown";
    public static final String NICK_CHANGE_COOLDOWN_KEY = "nick-change-cooldown";
    public static final String REPORT_SEND_COOLDOWN_KEY = "report-send-cooldown";
    public static final String PARTY_WARN_COOLDOWN_KEY = "party-warn-cooldown";
    public static final String PLAYERS_VISIBILITY_COOLDOWN_KEY = "players-visibility-cooldown";

    /* Menu Base64 Arcades */
    public static final String DUELS_SIMULATOR_BASE64 = "rO0ABXcEAAAAG3VyAAJbQqzzF/gGCFTgAgAAeHAAAABIH4sIAAAAAAAAAONiYOBgYMpMYRDNzcxLTS5KTCuxyizKz4vPSM3JTS1hZGB1zi/NK2FkYmBzScxNTE9lYGAAAMk6rGw0AAAAdXEAfgAAAAAATB+LCAAAAAAAAADjYmDgYGDKTGGQzM3MS00uSkwrscosys+LT85ILS4pyEksSWVkYHXOL80rYWRiYHNJzE1MT2VgYAAAH4jQATgAAAB1cQB+AAAAAABKH4sIAAAAAAAAAONiYOBgYMpMYRDPzcxLTS5KTCuxyizKz4vPSU1Pz8xLL2ZkYHXOL80rYWRiYHNJzE1MT2VgYAAA7APljzYAAAB1cQB+AAAAAABHH4sIAAAAAAAAAONiYOBgYMpMYRDJzcxLTS5KTCuxyizKz4tPys8vKWZkYHXOL80rYWRiYHNJzE1MT2VgYAAA6R5uMzMAAAB1cQB+AAAAAABBH4sIAAAAAAAAAONiYOBgYMpMYeDLzcxLTS5KTCuxSsovz2FkYHXOL80rcWBiYHNJzE1MT2VgYAAAv++QtS0AAAB1cQB+AAAAAABJH4sIAAAAAAAAAONiYOBgYMpMYRDLzcxLTS5KTCuxKkpNic8tLc4oys/PZWRgdc4vzStxYGJgc0nMTUxPZWBgAAC2ZHCoNQAAAHVxAH4AAAAAAEsfiwgAAAAAAAAA42Jg4GBgykxhkMjNzEtNLkpMK7FKKsovz4vPLS3OKMrPz2VkYHXOL80rcWBiYHNJzE1MT2VgYAAAqPPYNDcAAAB1cQB+AAAAAABAH4sIAAAAAAAAAONiYOBgYMpMYeDNzcxLTS5KTCuxSqlMZWRgdc4vzStxYGJgc0nMTUxPZWBmAADWlWFDLAAAAHVxAH4AAAAAAEofiwgAAAAAAAAA42Jg4GBgykxhEM/NzEtNLkpMK7EqLsnPS40vyEzOTqxIZWRgdc4vzSthZGJgc0nMTUxPZWBgAAB2ls0ZNgAAAHVxAH4AAAAAAEgfiwgAAAAAAAAA42Jg4GBgykxhEM3NzEtNLkpMK7HKLMrPi89IzclNLWFkYHXOL80rYWRiYHNJzE1MT2VgYAAAyTqsbDQAAAB1cQB+AAAAAABMH4sIAAAAAAAAAONiYOBgYMpMYZDMzcxLTS5KTCuxyizKz4tPzkgtLinISSxJZWRgdc4vzSthZGJgc0nMTUxPZWBgAAAfiNABOAAAAHVxAH4AAAAAAEofiwgAAAAAAAAA42Jg4GBgykxhEM/NzEtNLkpMK7HKLMrPi89JTU/PzEsvZmRgdc4vzSthZGJgc0nMTUxPZWBgAADsA+WPNgAAAHVxAH4AAAAAAEcfiwgAAAAAAAAA42Jg4GBgykxhEMnNzEtNLkpMK7HKLMrPi0/Kzy8pZmRgdc4vzSthZGJgc0nMTUxPZWBgAADpHm4zMwAAAHVxAH4AAAAAAEEfiwgAAAAAAAAA42Jg4GBgykxh4MvNzEtNLkpMK7FKyi/PYWRgdc4vzStxYGJgc0nMTUxPZWBgAAC/75C1LQAAAHVxAH4AAAAAAEkfiwgAAAAAAAAA42Jg4GBgykxhEMvNzEtNLkpMK7EqSk2Jzy0tzijKz89lZGB1zi/NK3FgYmBzScxNTE9lYGAAALZkcKg1AAAAdXEAfgAAAAAASx+LCAAAAAAAAADjYmDgYGDKTGGQyM3MS00uSkwrsUoqyi/Pi88tLc4oys/PZWRgdc4vzStxYGJgc0nMTUxPZWBgAACo89g0NwAAAHVxAH4AAAAAAEAfiwgAAAAAAAAA42Jg4GBgykxh4M3NzEtNLkpMK7FKqUxlZGB1zi/NK3FgYmBzScxNTE9lYGYAANaVYUMsAAAAdXEAfgAAAAAARh+LCAAAAAAAAADjYmDgYGDKTGEQzs3MS00uSkwrsSouyc9LjU+sSGVkYHXOL80rYWRiYHNJzE1MT2VgYAAAQU+52TIAAAB1cQB+AAAAAABIH4sIAAAAAAAAAONiYOBgYMpMYRDNzcxLTS5KTCuxykksS4xPKk3OTi1hZGB1zi/NK2FkYmBzScxNTE9lYGAAAAEaRN40AAAAdXEAfgAAAAAASB+LCAAAAAAAAADjYmDgYGDKTGEQzc3MS00uSkwrscpJLEuMTypNzk4tYWRgdc4vzSthZGJgc0nMTUxPZWBgAAABGkTeNAAAAHVxAH4AAAAAAEkfiwgAAAAAAAAA42Jg4GBgykxhEMvNzEtNLkpMK7EqTyxJLYpPKk3OTi1hZGB1zi/NK2FkYmBzScxNTE9lYGAAAApDDvU1AAAAdXEAfgAAAAAASh+LCAAAAAAAAADjYmDgYGDKTGEQz83MS00uSkwrscotLc4oys/PjS8uSS1nZGB1zi/NK2FkYmBzScxNTE9lYGAAAJOMA8U2AAAAdXEAfgAAAAAASh+LCAAAAAAAAADjYmDgYGDKTGEQz83MS00uSkwrscotLc4oys/PjS8uSS1nZGB1zi/NK2FkYmBzScxNTE9lYGAAAJOMA8U2AAAAdXEAfgAAAAAASh+LCAAAAAAAAADjYmDgYGDKTGEQz83MS00uSkwrscotLc4oys/PjS8uSS1nZGB1zi/NK2FkYmBzScxNTE9lYGAAAJOMA8U2AAAAdXEAfgAAAAAASh+LCAAAAAAAAADjYmDgYGDKTGEQz83MS00uSkwrscotLc4oys/PjS8uSS1nZGB1zi/NK2FkYmBzScxNTE9lYGAAAJOMA8U2AAAAdXEAfgAAAAAASh+LCAAAAAAAAADjYmDgYGDKTGEQz83MS00uSkwrscotLc4oys/PjS8uSS1nZGB1zi/NK2FkYmBzScxNTE9lYGAAAJOMA8U2AAAAdXEAfgAAAAAASh+LCAAAAAAAAADjYmDgYGDKTGEQz83MS00uSkwrscotLc4oys/PjS8uSS1nZGB1zi/NK2FkYmBzScxNTE9lYGAAAJOMA8U2AAAA @ rO0ABXcEAAAACXVyAAJbQqzzF/gGCFTgAgAAeHAAAABHH4sIAAAAAAAAAONiYOBgYMpMYRDJzcxLTS5KTCuxyizKz4svLs8vSmFkYHXOL80rYWRiYHNJzE1MT2VgYAAApFHZKzMAAAB1cQB+AAAAAABNH4sIAAAAAAAAAONiYOBgYMpMYZDKzcxLTS5KTCuxSs5PSspJLS7Jz0uNL0/MyWFkYHXOL80rcWBiYHNJzE1MT2VgYAAAnPlLjzkAAAB1cQB+AAAAAABIH4sIAAAAAAAAAONiYOBgYMpMYRDNzcxLTS5KTCuxykksS4xPKk3OTi1hZGB1zi/NK2FkYmBzScxNTE9lYGAAAAEaRN40AAAAdXEAfgAAAAAASR+LCAAAAAAAAADjYmDgYGDKTGEQy83MS00uSkwrsSpPLEktik8qTc5OLWFkYHXOL80rYWRiYHNJzE1MT2VgYAAACkMO9TUAAAB1cQB+AAAAAABKH4sIAAAAAAAAAONiYOBgYMpMYRDPzcxLTS5KTCuxyi0tzijKz8+NLy5JLWdkYHXOL80rYWRiYHNJzE1MT2VgYAAAk4wDxTYAAAB1cQB+AAAAAABKH4sIAAAAAAAAAONiYOBgYMpMYRDPzcxLTS5KTCuxyi0tzijKz8+NLy5JLWdkYHXOL80rYWRiYHNJzE1MT2VgYAAAk4wDxTYAAAB1cQB+AAAAAABKH4sIAAAAAAAAAONiYOBgYMpMYRDPzcxLTS5KTCuxyi0tzijKz8+NLy5JLWdkYHXOL80rYWRiYHNJzE1MT2VgYAAAk4wDxTYAAAB1cQB+AAAAAABAH4sIAAAAAAAAAONiYOBgYMpMYeDNzcxLTS5KTCuxKk9NYmRgdc4vzSthYWJgc0nMTUxPZWBgAACEsUNWLAAAAHVxAH4AAAAAAEMfiwgAAAAAAAAA42Jg4GBgykxhEMjNzEtNLkpMK7EqyEnMyy5mZGB1zi/NK3FgYmBzScxNTE9lYGAAAHoppUgvAAAA";
    public static final String DUELS_UHC_BASE64 = "rO0ABXcEAAAAG3VyAAJbQqzzF/gGCFTgAgAAeHAAAABCH4sIAAAAAAAAAONiYOBgYMpMYeDPzcxLTS5KTCuxSiwqyi9nZGB1zi/NKxFgYmBzScxNTE9lYGAAAA62ykkuAAAAcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHB1cQB+AAAAAABIH4sIAAAAAAAAAONiYOBgYMpMYRDNzcxLTS5KTCuxykksS4xPKk3OTi1hZGB1zi/NK2FkYmBzScxNTE9lYGAAAAEaRN40AAAAdXEAfgAAAAAASR+LCAAAAAAAAADjYmDgYGDKTGEQy83MS00uSkwrsSpPLEktik8qTc5OLWFkYHXOL80rYWRiYHNJzE1MT2VgYAAACkMO9TUAAAB1cQB+AAAAAABDH4sIAAAAAAAAAONiYOBgYMpMYRDIzcxLTS5KTCuxKshJzMsuZmRgdc4vzStxYGJgc0nMTUxPZWBgAAB6KaVILwAAAA== @ rO0ABXcEAAAACXVyAAJbQqzzF/gGCFTgAgAAeHAAAABwH4sIAAAAAAAAABWMQQqAIBQFn1pRrtp1l7Z1gi4QH7USUkOtrl+uhoFhJNCCW43BWW9UpC2P2pILXq/pDVEz1FO4fWYSItPeoTJeHRIA4xDncxaWQQ8BuZiLbJxCyiUARzOTo9389gENfN5OagAAAHVxAH4AAAAAAEgfiwgAAAAAAAAA42Jg4GBgykxhEM3NzEtNLkpMK7FKyyzOyMxLjy/KT2FkYHXOL80rYWRiYHNJzE1MT2VgYAAAVIsBETQAAAB1cQB+AAAAAABqH4sIAAAAAAAAAB3LSw5AMBRG4b+3CE3sxdiUFdjBVVVNqhWK7XsMT/IdBZQgN6FeXTB65zm1Y7wF8i6eIQkFmdhWyEzQiwIgCNJfHkT/1kBCDWZjt3fxSB8Aoeh5ZWveegDywTz2YAAAAHVxAH4AAAAAAEgfiwgAAAAAAAAA42Jg4GBgykxhEM3NzEtNLkpMK7FKyUzMzc9LiU+sSGVkYHXOL80rYWRiYHNJzE1MT2VgYAAAJ4j9pTQAAAB1cQB+AAAAAABJH4sIAAAAAAAAAONiYOBgYMpMYRDLzcxLTS5KTCuxSs/PSUnNi08sKMhJZWRgdc4vzSthY2Jgc0nMTUxPZWBgAAD8LLQUNQAAAHVxAH4AAAAAAVEfiwgAAAAAAAAATY9LcoJAGIR/NSaETSo3yCJbqkbkIanKIqWWDiUQ3zK7EQYBB7R4JOCFvEBOkFwsZJdld3/fokUAAdqRDw9JlDIvo0Hxkh9LzlvQHZ7KtOiI0CnoQQRx+Vc7nynLGgP78KwipAdyEEi6hnRJ0RiVDN9XJC0IDG3Q2w+QrzTee3Y6s6yIWH4PQsGqosxYLgJAS4DuhvKSwRerTUR2IfJ3JvdqrDV5tUTcwfFZx+mm3g+xhpNmn75ps9r4x6oF3arc7ZshSeflPtmgWX/B2XTR85L1hxVjxY5D7l7I0U0WkRuTiGztxI6PCpmMK+tCuC2PZVee185kXTkrq7JHntoQ3IpJaDWLLc9ld4tle0W4G+PKWZpGsEOvzQMR7vwoP3NaC3Bj04TB4/dVs+jPlT4Ny4z6p4wCtOF2RBN6YNCBXzkOyBpwAQAAdXEAfgAAAAAASB+LCAAAAAAAAADjYmDgYGDKTGEQzc3MS00uSkwrscpJLEuMTypNzk4tYWRgdc4vzSthZGJgc0nMTUxPZWBgAAABGkTeNAAAAHVxAH4AAAAAAEkfiwgAAAAAAAAA42Jg4GBgykxhEMvNzEtNLkpMK7EqTyxJLYpPKk3OTi1hZGB1zi/NK2FkYmBzScxNTE9lYGAAAApDDvU1AAAAdXEAfgAAAAAAQx+LCAAAAAAAAADjYmDgYGDKTGEQyM3MS00uSkwrsSrISczLLmZkYHXOL80rcWBiYHNJzE1MT2VgYAAAeimlSC8AAAA=";
    public static final String DUELS_NO_DEBUFF_BASE64 = "rO0ABXcEAAAAG3BwcHBwcHBwdXIAAltCrPMX+AYIVOACAAB4cAAAAEMfiwgAAAAAAAAA42Jg4GBgykxhEMjNzEtNLkpMK7EqyC/JzM9jZGB1zi/NK2FkYmBzScxNTE9VUGIAAJJ8TikvAAAAcHBwcHBwcHB1cQB+AAAAAABDH4sIAAAAAAAAAONiYOBgYMpMYRDIzcxLTS5KTCuxKsgvyczPY2Rgdc4vzSthZGJgc0nMTUxPVVBiAACSfE4pLwAAAHBwcHBwcHBwdXEAfgAAAAAAQx+LCAAAAAAAAADjYmDgYGDKTGEQyM3MS00uSkwrsSrIL8nMz2NkYHXOL80rYWRiYHNJzE1MT1VQYgAAknxOKS8AAAA= @ rO0ABXcEAAAACXVyAAJbQqzzF/gGCFTgAgAAeHAAAACAH4sIAAAAAAAAAONiYOBgYMpMYRDPzcxLTS5KTCuxSslMzM3PS4kvLs8vSmFkYHXOL80rYeRiYC5JTOdkYEnNS87gYmBgYGZiYM4pywHRIAMEGFD5SjA+E4QvwsDMwBWUWpCYWeScX1wCNIAdqILNJTE3MT0VyAMAun8IV4oAAAB1cQB+AAAAAABIH4sIAAAAAAAAAONiYOBgYMpMYRDNzcxLTS5KTCuxSs1LSS2KL0hNLMphZGB1zi/NKxFgYmBzScxNTE9lYGAAAHHXa3w0AAAAdXEAfgAAAAAAQx+LCAAAAAAAAADjYmDgYGDKTGEQyM3MS00uSkwrsSrIL8nMz2NkYHXOL80rYWRiYHNJzE1MT1VQYgAAknxOKS8AAAB1cQB+AAAAAABDH4sIAAAAAAAAAONiYOBgYMpMYRDIzcxLTS5KTCuxKsgvyczPY2Rgdc4vzSthZGJgc0nMTUxPVXBmAAB0JqhVLwAAAHBwcHB1cQB+AAAAAABIH4sIAAAAAAAAAONiYOBgYMpMYRDNzcxLTS5KTCuxSs7Pz05NiU9KTU1jZGB1zi/NK3FgYmBzScxNTE9lYGAAAEdgT7g0AAAA";
    public static final String DUELS_GLADIATOR_BASE64 = "rO0ABXcEAAAAG3VyAAJbQqzzF/gGCFTgAgAAeHAAAABIH4sIAAAAAAAAAONiYOBgYMpMYRDNzcxLTS5KTCuxyizKz4vPSM3JTS1hZGB1zi/NK2FkYmBzScxNTE9lYGAAAMk6rGw0AAAAdXEAfgAAAAAATB+LCAAAAAAAAADjYmDgYGDKTGGQzM3MS00uSkwrscosys+LT85ILS4pyEksSWVkYHXOL80rYWRiYHNJzE1MT2VgYAAAH4jQATgAAAB1cQB+AAAAAABKH4sIAAAAAAAAAONiYOBgYMpMYRDPzcxLTS5KTCuxyizKz4vPSU1Pz8xLL2ZkYHXOL80rYWRiYHNJzE1MT2VgYAAA7APljzYAAAB1cQB+AAAAAABHH4sIAAAAAAAAAONiYOBgYMpMYRDJzcxLTS5KTCuxyizKz4tPys8vKWZkYHXOL80rYWRiYHNJzE1MT2VgYAAA6R5uMzMAAAB1cQB+AAAAAABBH4sIAAAAAAAAAONiYOBgYMpMYeDLzcxLTS5KTCuxSsovz2FkYHXOL80rcWBiYHNJzE1MT2VgYAAAv++QtS0AAAB1cQB+AAAAAABAH4sIAAAAAAAAAONiYOBgYMpMYeDNzcxLTS5KTCuxSqlMZWRgdc4vzStxYGJgc0nMTUxPZWBmAADWlWFDLAAAAHVxAH4AAAAAAEAfiwgAAAAAAAAA42Jg4GBgykxh4M3NzEtNLkpMK7FKqUxlZGB1zi/NK3FgYmBzScxNTE9lYGYAANaVYUMsAAAAdXEAfgAAAAAAQB+LCAAAAAAAAADjYmDgYGDKTGHgzc3MS00uSkwrsUqpTGVkYHXOL80rcWBiYHNJzE1MT2VgZgAA1pVhQywAAAB1cQB+AAAAAABGH4sIAAAAAAAAAONiYOBgYMpMYRDOzcxLTS5KTCuxKi7Jz0uNT6xIZWRgdc4vzSthZGJgc0nMTUxPZWBgAABBT7nZMgAAAHVxAH4AAAAAAEgfiwgAAAAAAAAA42Jg4GBgykxhEM3NzEtNLkpMK7HKLMrPi89IzclNLWFkYHXOL80rYWRiYHNJzE1MT2VgYAAAyTqsbDQAAAB1cQB+AAAAAABMH4sIAAAAAAAAAONiYOBgYMpMYZDMzcxLTS5KTCuxyizKz4tPzkgtLinISSxJZWRgdc4vzSthZGJgc0nMTUxPZWBgAAAfiNABOAAAAHVxAH4AAAAAAEofiwgAAAAAAAAA42Jg4GBgykxhEM/NzEtNLkpMK7HKLMrPi89JTU/PzEsvZmRgdc4vzSthZGJgc0nMTUxPZWBgAADsA+WPNgAAAHVxAH4AAAAAAEcfiwgAAAAAAAAA42Jg4GBgykxhEMnNzEtNLkpMK7HKLMrPi0/Kzy8pZmRgdc4vzSthZGJgc0nMTUxPZWBgAADpHm4zMwAAAHVxAH4AAAAAAEEfiwgAAAAAAAAA42Jg4GBgykxh4MvNzEtNLkpMK7FKyi/PYWRgdc4vzStxYGJgc0nMTUxPZWBgAAC/75C1LQAAAHVxAH4AAAAAAEAfiwgAAAAAAAAA42Jg4GBgykxh4M3NzEtNLkpMK7FKqUxlZGB1zi/NK3FgYmBzScxNTE9lYGYAANaVYUMsAAAAdXEAfgAAAAAAQB+LCAAAAAAAAADjYmDgYGDKTGHgzc3MS00uSkwrsUqpTGVkYHXOL80rcWBiYHNJzE1MT2VgZgAA1pVhQywAAAB1cQB+AAAAAABAH4sIAAAAAAAAAONiYOBgYMpMYeDNzcxLTS5KTCuxSqlMZWRgdc4vzStxYGJgc0nMTUxPZWBmAADWlWFDLAAAAHVxAH4AAAAAAEofiwgAAAAAAAAA42Jg4GBgykxhEM/NzEtNLkpMK7EqLsnPS40vyEzOTqxIZWRgdc4vzSthZGJgc0nMTUxPZWBgAAB2ls0ZNgAAAHVxAH4AAAAAAEgfiwgAAAAAAAAA42Jg4GBgykxhEM3NzEtNLkpMK7HKSSxLjE8qTc5OLWFkYHXOL80rYWRiYHNJzE1MT2VgYAAAARpE3jQAAAB1cQB+AAAAAABIH4sIAAAAAAAAAONiYOBgYMpMYRDNzcxLTS5KTCuxykksS4xPKk3OTi1hZGB1zi/NK2FkYmBzScxNTE9lYGAAAAEaRN40AAAAcHBwcHBwcA== @ rO0ABXcEAAAACXVyAAJbQqzzF/gGCFTgAgAAeHAAAABwH4sIAAAAAAAAABWMQQqAIBQFn1pRrtp1l7Z1gi4QH7USUkOtrl+uhoFhJNCCW43BWW9UpC2P2pILXq/pDVEz1FO4fWYSItPeoTJeHRIA4xDncxaWQQ8BuZiLbJxCyiUARzOTo9389gENfN5OagAAAHVxAH4AAAAAAEkfiwgAAAAAAAAA42Jg4GBgykxhEMvNzEtNLkpMK7EqTyxJLYpPKk3OTi1hZGB1zi/NK2FkYmBzScxNTE9lYGAAAApDDvU1AAAAdXEAfgAAAAAASB+LCAAAAAAAAADjYmDgYGDKTGEQzc3MS00uSkwrscpJLEuMTypNzk4tYWRgdc4vzSthZGJgc0nMTUxPZWBgAAABGkTeNAAAAHVxAH4AAAAAAEMfiwgAAAAAAAAA42Jg4GBgykxhEMjNzEtNLkpMK7EqyEnMyy5mZGB1zi/NK3FgYmBzScxNTE9lYGAAAHoppUgvAAAAcHBwcHVxAH4AAAAAAE0fiwgAAAAAAAAA42Jg4GBgykxhkMrNzEtNLkpMK7FKzk9KykktLsnPS40vT8zJYWRgdc4vzStxYGJgc0nMTUxPZWBgAACc+UuPOQAAAA==";
    public static final String DUELS_THE_BRIDGE_BASE64 = "rO0ABXcEAAAAG3BwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcA== @ rO0ABXcEAAAACXVyAAJbQqzzF/gGCFTgAgAAeHAAAABaH4sIAAAAAAAAAAXBQQ5AMBAF0D+ESG2dxpYrWMtUR9PQaTIqru89BwxoUsCUk8phfNY5WdH9+YoFQreUVys5tJUjYdzUm/DF/hZCg37lzFEA/PkJ13FJAAAAdXEAfgAAAAAAVR+LCAAAAAAAAAAFwdEJgDAMBcCXiiIVF/JXV3CARGMp2hRKxPW9i8CIkE/MJZsejS9fpH6Efq2vOUV0zokw7SZN+WZ5lBAwbFw4KYAfOVHxe0IAAAB1cQB+AAAAAACBH4sIAAAAAAAAAB3MSQ7CMBAF0e82IDAnYMc52CYnQMoadewmtOIhcgzi+AzLkp7KAXuQBpySZvGV7+0SlFPJ4baon/ktBtuuPHMzDrbxdMBGsn84AIZg4yuC6L84w+A45LEKzzxGMRbuKgtr7crafh6EXc+JJ/nWB8FsoCl7AAAAdXEAfgAAAAAATh+LCAAAAAAAAADjYmDgYGDKTGGQz83MS00uSkwrsSouSQSyU+IzEotSUkGM5JzESkYGVuf80rwSByYGNpfE3MT0VAYGBgBdA9XgPgAAAHVxAH4AAAAAAE4fiwgAAAAAAAAA42Jg4GBgykxhkM/NzEtNLkpMK7EqLkkEslPiMxKLUlJBjOScxEpGBlbn/NK8EgcmBjaXxNzE9FQGBgYAXQPV4D4AAAB1cQB+AAAAAABJH4sIAAAAAAAAAONiYOBgYMpMYRDLzcxLTS5KTCuxSs/PSUnNi08sKMhJZWRgdc4vzSvhYGJgc0nMTUxPZWBgAABMIFLuNQAAAHBwdXEAfgAAAAAAQh+LCAAAAAAAAADjYmDgYGDKTGHgz83MS00uSkwrsUosKsovZ2Rgdc4vzSthZGJgc0nMTUxPZWBgAABRyVsgLgAAAA==";
    public static final String DUELS_FIREBALL_BASE64 = "rO0ABXcEAAAAG3BwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcA== @ rO0ABXcEAAAACXVyAAJbQqzzF/gGCFTgAgAAeHAAAABbH4sIAAAAAAAAAAXBQQqAIBAF0D9GEbbuMm3rCq1jzEmkHEGNrt97FhhhosecospZ+GpLbVnlqF8untCv+dVGFl3jQJh2dUX4ZvcIwWDYOHEQAD++W2m3SgAAAHVxAH4AAAAAAEEfiwgAAAAAAAAA42Jg4GBgykxh4MvNzEtNLkpMK7Eqz8/PYWRgdc4vzStxYGJgc0nMTUxPZWBgAABO13qyLQAAAHVxAH4AAAAAAEYfiwgAAAAAAAAA42Jg4GBgykxhEM7NzEtNLkpMK7FKzUuJLy7Jz0tlZGB1zi/NK+FgYmBzScxNTE9lYGAAACy3NXgyAAAAdXEAfgAAAAAASB+LCAAAAAAAAADjYmDgYGDKTGEQzc3MS00uSkwrsUrLLEqNT85ILEpPZWRgdc4vzSthY2Jgc0nMTUxPZWBgAAA8LSYaNAAAAHVxAH4AAAAAAEAfiwgAAAAAAAAA42Jg4GBgykxh4M3NzEtNLkpMK7EqySthZGB1zi/NK2FiYmBzScxNTE9lYGAAAKut4gMsAAAAdXEAfgAAAAAAfx+LCAAAAAAAAAAVjMEOgjAQBd+2aLT+gEe/wyt+gYlnspQFG8qW1Ip+vvY0mWQyDjjAhAHnJaj4zGO5flIaRLs1+Jm/Qti16a2FHGzh6YhG1D8dADKwcYuV9XAB4fTQPgvP3EchC3eXlUNu06vUHgb7Gy88yd9+xO0HKnoAAAB1cQB+AAAAAAB8H4sIAAAAAAAAABWLwQ6CMBAF37ZKtF79AL+DK3yBCWeywIqNZUtKRT9fe5pMMuOAE4yfcF28ypj4ketPjJNoz18hHJv41kwONvN8xkF0fDoAZGDDHgrLfQPh0umQhF88BCELd5eVfWrilksPg6rlhWf52w+n2aqadgAAAHVxAH4AAAAAAFcfiwgAAAAAAAAABcHBDYAgEATAPYzG4Md6/GoLFrDoiUTBBLB/ZiwwwoQTcwxJj8yrLuVW5iLo1+9PVSy6Si+Y9uSy8qF7VWAwbIz0CqABtnXyzEUAAAB1cQB+AAAAAABDH4sIAAAAAAAAAONiYOBgYMpMYRDIzcxLTS5KTCuxyklMSUktYmRgdc4vzSvhYGJgc0nMTUxPZWBgAAALH2dlLwAAAA==";


}
